#trigger:
#- task: Application security testing@2024
#  inputs:
#    projectName: 'Cxsast_azure'
#    enableProxy: false
#    enableSastScan: true
#    enableSastBranching: true
#    masterBranchProjectName: 'main'
#    enableDependencyScan: false
#- main

pool:
  name: default
  

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  
- task: Checkmarx AST@2
  inputs:
    CheckmarxService: 'CxONE connection'
    projectName: '$(Build.Repository.Name)'
    branchName: '$(Build.SourceBranchName)'
    tenantName: 'ast_abdul_ansari'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
