# Starter pipeline
trigger:
  - main

pool:
  vmImage: 'default'  # You can specify the VM image to use; replace with 'default' if needed.

steps:
  # Checkmarx AST task for static analysis
  - task: Checkmarx AST@3
    inputs:
      CheckmarxService: 'cxone_ast'
      projectName: '$(Build.Repository.Name)'
      branchName: '$(Build.SourceBranchName)'

  # Simple script to display a hello world message
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  # Multi-line script to display additional messages
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
