trigger:
- main
 
pool:
      name: Default
 
steps:
 
 

- task: Checkmarx AST@3
  inputs:
    CheckmarxService: 'cxone_ast'
    projectName: '$(Build.Repository.Name)'
    branchName: '$(Build.SourceBranchName)'
