name: Security Scan and Deployment Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch

jobs:
  security-scan:
    runs-on: self-hosted
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Security Scan Step
      - name: Run Checkmarx Security Scan
        env:
          CHECKMARX_URL: "http://sudhat-lt/"
          CHECKMARX_API_TOKEN: ${{ secrets.CHECKMARX_API_TOKEN }}
          CHECKMARX_USERNAME: "sudha"
          CHECKMARX_PASSWORD: "Ramji@2811"
          CHECKMARX_CLIENT_ID: "resource_owner_client"
          CHECKMARX_CLIENT_SECRET: "014DF517-39D1-4453-B7B3-9930C563627C"
          CHECKMARX_SCOPE: "access_control_api sast_rest_api"
        run: |
          echo "Running Checkmarx security scan..."
          curl -v -X POST "${CHECKMARX_URL}/cxrestapi/sast/scans" \
            -H "Authorization: Bearer ${CHECKMARX_API_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{
                  "name": "GitHub Scan",
                  "projectId": "YOUR_PROJECT_ID",
                  "branch": "main",
                  "presetId": "Checkmarx Default",
                  "configuration": "Default Configuration",
                  "filter": {"categories": ["SQL_Injection", "Stored_XSS", "Reflected_XSS_All_Clients"]}
                }'

  deploy:
    needs: security-scan
    runs-on: ubuntu-latest
    environment:
      name: staging

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy to Staging
      - name: Deploy to Staging
        run: |
          echo "Deploying to staging environment..."
          ./deploy-to-staging.sh  # Replace with your script or commands

  production-deploy:
    needs: deploy
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://your-production-url.com  # Optional production URL

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy to Production
      - name: Deploy to Production
        run: |
          echo "Deploying to production environment..."
          ./deploy-to-production.sh  # Replace with your script or commands
