name: Checkmarx DAST Pipeline
 
on: 

  # No trigger here, this pipeline will not run automatically.

  # You can add a manual trigger like the following if needed:

   workflow_dispatch:
 
jobs:

  checkmarx-dast:

    permissions:

      contents: read

      security-events: write

      actions: read
 
    runs-on: ubuntu-latest
 
    steps:

      - name: Checkout Repository

        uses: actions/checkout@v3
 
      - name: Create Directory for Output

        run: mkdir ${{ github.workspace }}/output_fold
 
      - name: Change Directory Owner

        run: sudo chown -R 1000:1000 ${{ github.workspace }}
 
      - name: Checkmarx DAST Scan

        uses: Checkmarx/dast-github-action@v2.3.0

        env:

          CX_APIKEY: ${{ secrets.CXONE_APIKEY }}   # add the secret name

        with:

          # The type of scan to perform (web, api)

          command: web

          # The path to the ZAP configuration file

          config: ../altoro_mutual_config.yaml   # need to chk yaml

          # The base URL for the Checkmarx One Servers

          base_url: https://eu.ast.checkmarx.net

          # The environment ID previously created in the Frontend

          environment_id: ac6ee651-55ec-4481-bdfb-21ecc1812701  # en_id from cxone

          output: ${{ github.workspace }}/output_fold #./output
 
      - name: Reclaim Output Directory

        if: always()

        run: sudo chown -R 1001:1001 ${{ github.workspace }}/output_fold
 
      - name: Upload DAST Logs

        uses: actions/upload-artifact@v4

        if: always()

        with:

          name: dast-report

          path: ${{ github.workspace }}/output_fold
