name: Security Scan and Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkmarx Security Scan
        uses: miguelfreitas93/checkmarx-github-action@v2.322.0  # Ensure you are using a valid version
        with:
          checkmarx_url: "http://sudhat-lt/"
          team: "/CxServer"
          checkmarx_username: sudha
          checkmarx_password: Ramji@2811
          checkmarx_client_secret: ${{ secrets.CHECKMARX_CLIENT_SECRET }}
          project: "YOUR_PROJECT_ID"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          scanners: "sast"
