name: Checkmarx SAST Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: miguelfreitas93/checkmarx-github-action@v1
      with:
        cxServer: http://sudhat-lt/
        cxUsername: sudha
        cxPassword: Ramji@2811
        cxTeam: \CxServer\SP\Company\TeamA
