on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
 
jobs:
  build:
    runs-on: self-hosted
 
    steps:
      - uses: actions/checkout@v3
      - name: Checkmarx CxFlow Action
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.0-9.x
        with:
          checkmarx_url: ${{secrets.CHECKMARX_SERVER}}
          team: /CxServer
          checkmarx_username: ${{secrets.CHECKMARX_USERNAME}}
          checkmarx_password: ${{secrets.CHECKMARX_PASSWORD}}
          checkmarx_client_secret: ${{secrets.CXSAST_CLIENT_SECRET}}
          project: github_chartJS
          
